### ISSUE TITLE
Lab 2 notes

### ISSUE THREAD

**Issue by AntonC9018** [kraaddys/Algorithm_Lab#1]
https://github.com/kraaddys/Algorithm_Lab/blob/ee53a9c7d6b94f85bcfe66e087aa29aabfd3ca1c/Lab%202/ASD_Lab_2/ASD_Lab2_Code1/ASD_Lab1_Code1/Source.cpp#L8-L9
Не ошибка, но в задании требуется *определить* переменную (то есть в 1 шаг). Убедись, что осознаешь разницу.

Все норм, только расскажи, откуда узнал термин "объект", потому что я такое не давал. Используется термин корректно.

**Comment by AntonC9018** [comment]
Ожидаю ответа? Напиши мне.

**Comment by kraaddys** [comment]
Добрый вечер. Исправленный вариант закину вместе с 3 лабораторной работой
сразу.

чт, 12 окт. 2023 г., 18:32 Anton Curmanschii ***@***.***>:

**Comment by AntonC9018** [comment]
В первом комменте есть вопрос. Ответь на него пожалуйста тоже.

**Comment by kraaddys** [comment]
Да, я понял про какие недочеты мы мне написали в первом пункте и исправлю
их тоже. Извините за столько долгие ответы, исправлюсь.

чт, 12 окт. 2023 г., 19:20 Anton Curmanschii ***@***.***>:

**Comment by AntonC9018** [comment]
Я имел ввиду вопрос про то, откуда знаешь понятие "объект". Ты программировал раньше уже что ли?

**Comment by kraaddys** [comment]
Да, я программировал. В прошлом году я уже учился тут в университете, но
решил перепоступить заново из-за нового учебного плана. У меня уже есть
небольшая база в программировании на С++.

чт, 12 окт. 2023 г., 19:44 Anton Curmanschii ***@***.***>:
